### ISSUE TITLE
Rollup template npm run build not producing index.js

### ISSUE THREAD

**Issue by matt3224** [sveltejs/sapper-template#101]
I've migrated from webpack to rollup and despite a few minor minor issues I got it to a point where I could push it live to replace my webpack build. However upon pushing to the server, clearing node_modules, running npm i, then npm run build and finally npm start, i'm seeing a failure.

Here's the log:
```log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.4.1
3 info using node@v8.12.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle HP-Docs@1.3.0~prestart: HP-Docs@1.3.0
6 info lifecycle HP-Docs@1.3.0~start: HP-Docs@1.3.0
7 verbose lifecycle HP-Docs@1.3.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle HP-Docs@1.3.0~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/runcloud/webapps/docs/frontend/node_modules/.bin:/home/runcloud/.local/bin:/RunCloud/Packages/httpd-rc/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle HP-Docs@1.3.0~start: CWD: /home/runcloud/webapps/docs/frontend
10 silly lifecycle HP-Docs@1.3.0~start: Args: [ '-c', 'node __sapper__/build' ]
11 silly lifecycle HP-Docs@1.3.0~start: Returned: code: 1  signal: null
12 info lifecycle HP-Docs@1.3.0~start: Failed to exec start script
13 verbose stack Error: HP-Docs@1.3.0 start: `node __sapper__/build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:915:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid HP-Docs@1.3.0
15 verbose cwd /home/runcloud/webapps/docs/frontend
16 verbose Linux 4.15.0-36-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v8.12.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error HP-Docs@1.3.0 start: `node __sapper__/build`
22 error Exit status 1
23 error Failed at the HP-Docs@1.3.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Looks like maybe __sapper__/build is missing the index.js perhaps?

**Comment by MaxMilton** [comment]
For general support questions you can post it on stackoverflow. I've seen Rich and others replying on there too, so you'll likely get a response :)
