### ISSUE TITLE
Error running in Powershell

### ISSUE THREAD

**Issue by ihildebrandt** [sveltejs/sapper-template#223]
Running `npm run dev` from Powershell causes the error below. I was able to run using CMD with no issues, so it seems to be a problem with only Powershell and not Windows in general. 

```
❯ npm run dev

> TODO@0.0.1 dev C:\dev\palladium\palladium-web-sapper
> sapper dev

✗ server
Could not resolve entry module (undefined\server.js).
✗ client
Could not resolve entry module (undefined\client.js).
internal/modules/cjs/loader.js:979
  throw err;
  ^

Error: Cannot find module 'C:\dev\palladium\palladium-web-sapper\__sapper__\dev\server\server.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:976:15)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
> Server crashed
✗ service worker
Could not resolve entry module (undefined\service-worker.js).
```

**Comment by dennismurigi** [comment]
I am getting that exact error on cmd, bash and powershell, using the webpack branch gives an error too. Not sure if it's a problem with sapper or windows.

**Comment by Conduitry** [comment]
Without a reproduction, there's not a lot that can be done here - and questions about environmental things like this should be directed to the chat or to StackOverflow.
