### ISSUE TITLE
Missing dependency `tslib`

### ISSUE THREAD

**Issue by rafistrauss** [sveltejs/sapper-template#47]
Hi - ran the setup instructions (on Windows 10) and after `npm install` tried running `npm run dev` - server fails to startup; `Cannot find module 'tslib'`. Adding `tslib` to the root package.json dependencies seems to fix it.

Here's the output:

```
C:\Users\Me\sapper\my-app>npm run dev

> TODO@0.0.1 dev C:\Users\Me\sapper\my-app
> sapper dev

module.js:557
    throw err;
    ^

Error: Cannot find module 'tslib'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Me\sapper\my-app\node_modules\sapper\dist\cli.ts.js:5:15)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! TODO@0.0.1 dev: `sapper dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the TODO@0.0.1 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Me\AppData\Roaming\npm-cache\_logs\2018-03-12T01_38_01_754Z-debug.log

```

**Comment by Rich-Harris** [comment]
whoops! temporary glitch — if you update Sapper to 0.9.6, it's fixed. Thanks for spotting it
